const ketVocabularyScene = {
    "家庭场景": [
        { word: "father", definition: "父亲", example: "My father is a doctor.", category: "家庭" },
        { word: "mother", definition: "母亲", example: "My mother is a teacher.", category: "家庭" },
        { word: "brother", definition: "兄弟", example: "I have a brother.", category: "家庭" },
        { word: "sister", definition: "姐妹", example: "She has a sister.", category: "家庭" },
        { word: "son", definition: "儿子", example: "They have a son.", category: "家庭" },
        { word: "daughter", definition: "女儿", example: "She has a daughter.", category: "家庭" },
        { word: "grandfather", definition: "祖父", example: "My grandfather is old.", category: "家庭" },
        { word: "grandmother", definition: "祖母", example: "My grandmother is kind.", category: "家庭" },
        { word: "uncle", definition: "叔叔", example: "My uncle is funny.", category: "家庭" },
        { word: "aunt", definition: "阿姨", example: "My aunt is pretty.", category: "家庭" },
        { word: "cousin", definition: "表兄弟姐妹", example: "My cousin is my friend.", category: "家庭" },
        { word: "family", definition: "家庭", example: "I love my family.", category: "家庭" },
        { word: "home", definition: "家", example: "Home is sweet.", category: "家庭" },
        { word: "house", definition: "房子", example: "This is my house.", category: "家庭" },
        { word: "room", definition: "房间", example: "My room is clean.", category: "家庭" },
        { word: "bedroom", definition: "卧室", example: "I sleep in the bedroom.", category: "家庭" },
        { word: "living room", definition: "客厅", example: "We watch TV in the living room.", category: "家庭" },
        { word: "kitchen", definition: "厨房", example: "My mother cooks in the kitchen.", category: "家庭" },
        { word: "bathroom", definition: "浴室", example: "I take a shower in the bathroom.", category: "家庭" },
        { word: "door", definition: "门", example: "Open the door.", category: "家庭" },
        { word: "window", definition: "窗户", example: "Close the window.", category: "家庭" },
        { word: "wall", definition: "墙", example: "The wall is white.", category: "家庭" },
        { word: "floor", definition: "地板", example: "The floor is clean.", category: "家庭" },
        { word: "ceiling", definition: "天花板", example: "The ceiling is high.", category: "家庭" },
        { word: "furniture", definition: "家具", example: "We bought new furniture.", category: "家庭" },
        { word: "table", definition: "桌子", example: "Put the book on the table.", category: "家庭" },
        { word: "chair", definition: "椅子", example: "Sit on the chair.", category: "家庭" },
        { word: "sofa", definition: "沙发", example: "I sit on the sofa.", category: "家庭" },
        { word: "bed", definition: "床", example: "I sleep on the bed.", category: "家庭" },
        { word: "desk", definition: "书桌", example: "I study at my desk.", category: "家庭" },
        { word: "bookshelf", definition: "书架", example: "Books are on the bookshelf.", category: "家庭" },
        { word: "lamp", definition: "灯", example: "Turn on the lamp.", category: "家庭" },
        { word: "television", definition: "电视", example: "We watch television.", category: "家庭" },
        { word: "computer", definition: "电脑", example: "I use the computer.", category: "家庭" },
        { word: "phone", definition: "电话", example: "Call me on the phone.", category: "家庭" },
        { word: "clock", definition: "钟表", example: "Look at the clock.", category: "家庭" },
        { word: "picture", definition: "图片", example: "That is a nice picture.", category: "家庭" },
        { word: "garden", definition: "花园", example: "We have a beautiful garden.", category: "家庭" },
        { word: "tree", definition: "树", example: "The tree is tall.", category: "家庭" },
        { word: "flower", definition: "花", example: "The flower is red.", category: "家庭" },
        { word: "grass", definition: "草", example: "Green grass.", category: "家庭" }
    ],
    "学校场景": [
        { word: "school", definition: "学校", example: "I go to school by bus.", category: "学校" },
        { word: "teacher", definition: "老师", example: "The teacher is nice.", category: "学校" },
        { word: "student", definition: "学生", example: "I am a student.", category: "学校" },
        { word: "classroom", definition: "教室", example: "We are in the classroom.", category: "学校" },
        { word: "class", definition: "班级/课", example: "Class starts at 8 am.", category: "学校" },
        { word: "lesson", definition: "课", example: "We have four lessons today.", category: "学校" },
        { word: "subject", definition: "科目", example: "English is my favorite subject.", category: "学校" },
        { word: "math", definition: "数学", example: "I like math.", category: "学校" },
        { word: "English", definition: "英语", example: "I study English every day.", category: "学校" },
        { word: "Chinese", definition: "语文", example: "Chinese is my first language.", category: "学校" },
        { word: "science", definition: "科学", example: "We do experiments in science class.", category: "学校" },
        { word: "history", definition: "历史", example: "History is interesting.", category: "学校" },
        { word: "geography", definition: "地理", example: "We learn about countries.", category: "学校" },
        { word: "music", definition: "音乐", example: "Music class is fun.", category: "学校" },
        { word: "art", definition: "美术", example: "I like drawing in art class.", category: "学校" },
        { word: "PE", definition: "体育", example: "We play sports in PE class.", category: "学校" },
        { word: "book", definition: "书", example: "I read a book.", category: "学校" },
        { word: "pen", definition: "钢笔", example: "I write with a pen.", category: "学校" },
        { word: "pencil", definition: "铅笔", example: "I use a pencil.", category: "学校" },
        { word: "eraser", definition: "橡皮", example: "I need an eraser.", category: "学校" },
        { word: "ruler", definition: "尺子", example: "I use a ruler.", category: "学校" },
        { word: "bag", definition: "书包", example: "Put books in the bag.", category: "学校" },
        { word: "blackboard", definition: "黑板", example: "Look at the blackboard.", category: "学校" },
        { word: "desk", definition: "课桌", example: "Put your book on the desk.", category: "学校" },
        { word: "homework", definition: "作业", example: "I do my homework.", category: "学校" },
        { word: "exam", definition: "考试", example: "We have an exam today.", category: "学校" },
        { word: "test", definition: "测试", example: "English test tomorrow.", category: "学校" },
        { word: "grade", definition: "年级", example: "I'm in Grade 5.", category: "学校" },
        { word: "learn", definition: "学习", example: "We learn new things.", category: "学校" },
        { word: "study", definition: "学习", example: "I study every day.", category: "学校" },
        { word: "teach", definition: "教", example: "Teachers teach students.", category: "学校" },
        { word: "read", definition: "读", example: "Read the book.", category: "学校" },
        { word: "write", definition: "写", example: "Write your name.", category: "学校" },
        { word: "listen", definition: "听", example: "Listen carefully.", category: "学校" },
        { word: "speak", definition: "说", example: "Speak English.", category: "学校" },
        { word: "understand", definition: "理解", example: "I understand now.", category: "学校" },
        { word: "remember", definition: "记住", example: "Remember the words.", category: "学校" },
        { word: "forget", definition: "忘记", example: "Don't forget.", category: "学校" },
        { word: "know", definition: "知道", example: "I know the answer.", category: "学校" },
        { word: "question", definition: "问题", example: "Ask a question.", category: "学校" },
        { word: "answer", definition: "回答", example: "Answer the question.", category: "学校" }
    ],
    "饮食场景": [
        { word: "food", definition: "食物", example: "Food is necessary.", category: "饮食" },
        { word: "eat", definition: "吃", example: "I eat breakfast.", category: "饮食" },
        { word: "drink", definition: "喝", example: "Drink some water.", category: "饮食" },
        { word: "breakfast", definition: "早餐", example: "Breakfast at 7 am.", category: "饮食" },
        { word: "lunch", definition: "午餐", example: "Lunch at noon.", category: "饮食" },
        { word: "dinner", definition: "晚餐", example: "Dinner at 6 pm.", category: "饮食" },
        { word: "meal", definition: "一餐", example: "Three meals a day.", category: "饮食" },
        { word: "bread", definition: "面包", example: "I eat bread for breakfast.", category: "饮食" },
        { word: "rice", definition: "米饭", example: "We eat rice.", category: "饮食" },
        { word: "noodle", definition: "面条", example: "Noodles are delicious.", category: "饮食" },
        { word: "egg", definition: "蛋", example: "Eggs are healthy.", category: "饮食" },
        { word: "milk", definition: "牛奶", example: "Drink milk every day.", category: "饮食" },
        { word: "water", definition: "水", example: "Water is important.", category: "饮食" },
        { word: "juice", definition: "果汁", example: "Orange juice is good.", category: "饮食" },
        { word: "coffee", definition: "咖啡", example: "Coffee is bitter.", category: "饮食" },
        { word: "tea", definition: "茶", example: "Chinese tea.", category: "饮食" },
        { word: "apple", definition: "苹果", example: "An apple a day.", category: "饮食" },
        { word: "banana", definition: "香蕉", example: "Bananas are sweet.", category: "饮食" },
        { word: "orange", definition: "橙子", example: "Oranges are healthy.", category: "饮食" },
        { word: "fruit", definition: "水果", example: "Eat more fruit.", category: "饮食" },
        { word: "vegetable", definition: "蔬菜", example: "Vegetables are good.", category: "饮食" },
        { word: "tomato", definition: "西红柿", example: "Tomatoes are red.", category: "饮食" },
        { word: "potato", definition: "土豆", example: "I like potatoes.", category: "饮食" },
        { word: "carrot", definition: "胡萝卜", example: "Carrots are orange.", category: "饮食" },
        { word: "meat", definition: "肉", example: "I don't eat meat.", category: "饮食" },
        { word: "chicken", definition: "鸡肉", example: "Chicken is popular.", category: "饮食" },
        { word: "fish", definition: "鱼", example: "Fish is healthy.", category: "饮食" },
        { word: "cake", definition: "蛋糕", example: "Birthday cake.", category: "饮食" },
        { word: "cookie", definition: "饼干", example: "Cookies are sweet.", category: "饮食" },
        { word: "sweet", definition: "甜的", example: "Candy is sweet.", category: "饮食" },
        { word: "sugar", definition: "糖", example: "Too much sugar.", category: "饮食" },
        { word: "salt", definition: "盐", example: "Add some salt.", category: "饮食" },
        { word: "hungry", definition: "饿的", example: "I'm hungry.", category: "饮食" },
        { word: "thirsty", definition: "渴的", example: "I'm thirsty.", category: "饮食" },
        { word: "full", definition: "饱的", example: "I am full.", category: "饮食" },
        { word: "delicious", definition: "美味的", example: "This is delicious.", category: "饮食" },
        { word: "good", definition: "好的", example: "Good food.", category: "饮食" },
        { word: "bad", definition: "坏的", example: "The food tastes bad.", category: "饮食" },
        { word: "cook", definition: "烹饪", example: "I can cook.", category: "饮食" },
        { word: "make", definition: "做", example: "Make dinner.", category: "饮食" },
        { word: "plate", definition: "盘子", example: "Put on plate.", category: "饮食" },
        { word: "bowl", definition: "碗", example: "Soup bowl.", category: "饮食" },
        { word: "cup", definition: "杯子", example: "Cup of tea.", category: "饮食" },
        { word: "spoon", definition: "勺子", example: "Use a spoon.", category: "饮食" },
        { word: "fork", definition: "叉子", example: "Fork and knife.", category: "饮食" },
        { word: "knife", definition: "刀", example: "Cut with knife.", category: "饮食" }
    ],
    "日常活动场景": [
        { word: "get up", definition: "起床", example: "I get up at 7.", category: "日常" },
        { word: "go to bed", definition: "睡觉", example: "Go to bed early.", category: "日常" },
        { word: "sleep", definition: "睡觉", example: "I sleep well.", category: "日常" },
        { word: "wake up", definition: "醒来", example: "I wake up early.", category: "日常" },
        { word: "brush teeth", definition: "刷牙", example: "Brush teeth every day.", category: "日常" },
        { word: "wash face", definition: "洗脸", example: "Wash your face.", category: "日常" },
        { word: "take a shower", definition: "洗澡", example: "I take a shower.", category: "日常" },
        { word: "have a bath", definition: "洗澡", example: "Have a bath.", category: "日常" },
        { word: "get dressed", definition: "穿衣服", example: "Get dressed quickly.", category: "日常" },
        { word: "wear", definition: "穿着", example: "I wear a coat.", category: "日常" },
        { word: "go to school", definition: "上学", example: "Go to school now.", category: "日常" },
        { word: "go home", definition: "回家", example: "Let's go home.", category: "日常" },
        { word: "come back", definition: "回来", example: "Come back soon.", category: "日常" },
        { word: "work", definition: "工作", example: "My father works.", category: "日常" },
        { word: "do homework", definition: "做作业", example: "Do your homework.", category: "日常" },
        { word: "read", definition: "阅读", example: "Read a book.", category: "日常" },
        { word: "write", definition: "写", example: "Write a letter.", category: "日常" },
        { word: "watch TV", definition: "看电视", example: "Watch TV together.", category: "日常" },
        { word: "listen to music", definition: "听音乐", example: "I like listening to music.", category: "日常" },
        { word: "play", definition: "玩", example: "Play with friends.", category: "日常" },
        { word: "play games", definition: "玩游戏", example: "Play computer games.", category: "日常" },
        { word: "play sports", definition: "做运动", example: "Play sports every day.", category: "日常" },
        { word: "run", definition: "跑", example: "Run fast.", category: "日常" },
        { word: "jump", definition: "跳", example: "Jump high.", category: "日常" },
        { word: "walk", definition: "走路", example: "Walk to school.", category: "日常" },
        { word: "go shopping", definition: "购物", example: "Let's go shopping.", category: "日常" },
        { word: "clean", definition: "打扫", example: "Clean the room.", category: "日常" },
        { word: "wash", definition: "洗", example: "Wash the dishes.", category: "日常" },
        { word: "cook", definition: "做饭", example: "Cook dinner.", category: "日常" },
        { word: "help", definition: "帮助", example: "Help your mom.", category: "日常" },
        { word: "talk", definition: "说话", example: "Talk to me.", category: "日常" },
        { word: "say", definition: "说", example: "Say it again.", category: "日常" },
        { word: "tell", definition: "告诉", example: "Tell a story.", category: "日常" },
        { word: "ask", definition: "问", example: "Ask questions.", category: "日常" },
        { word: "answer", definition: "回答", example: "Answer me.", category: "日常" },
        { word: "think", definition: "想", example: "Think carefully.", category: "日常" },
        { word: "feel", definition: "感觉", example: "How do you feel?", category: "日常" },
        { word: "happy", definition: "开心的", example: "I'm very happy.", category: "日常" },
        { word: "sad", definition: "难过的", example: "I'm sad today.", category: "日常" },
        { word: "excited", definition: "激动的", example: "I'm so excited!", category: "日常" },
        { word: "tired", definition: "累的", example: "I'm tired.", category: "日常" },
        { word: "surprised", definition: "惊讶的", example: "I'm surprised!", category: "日常" },
        { word: "afraid", definition: "害怕的", example: "Don't be afraid.", category: "日常" },
        { word: "love", definition: "爱", example: "I love you.", category: "日常" },
        { word: "like", definition: "喜欢", example: "I like this.", category: "日常" },
        { word: "want", definition: "想要", example: "What do you want?", category: "日常" },
        { word: "need", definition: "需要", example: "I need a pen.", category: "日常" },
        { word: "have", definition: "有", example: "I have a dog.", category: "日常" },
        { word: "make", definition: "做", example: "Make a cake.", category: "日常" },
        { word: "do", definition: "做", example: "What do you do?", category: "日常" },
        { word: "see", definition: "看见", example: "I see you.", category: "日常" },
        { word: "look", definition: "看", example: "Look at that.", category: "日常" },
        { word: "hear", definition: "听见", example: "I hear music.", category: "日常" },
        { word: "listen", definition: "听", example: "Listen carefully.", category: "日常" }
    ],
    "交通旅行场景": [
        { word: "go", definition: "去", example: "Let's go!", category: "交通" },
        { word: "come", definition: "来", example: "Come here.", category: "交通" },
        { word: "leave", definition: "离开", example: "Leave now.", category: "交通" },
        { word: "arrive", definition: "到达", example: "Arrive on time.", category: "交通" },
        { word: "walk", definition: "走路", example: "Walk there.", category: "交通" },
        { word: "ride", definition: "骑", example: "Ride a bike.", category: "交通" },
        { word: "drive", definition: "开车", example: "Drive carefully.", category: "交通" },
        { word: "fly", definition: "飞", example: "Fly to Beijing.", category: "交通" },
        { word: "car", definition: "汽车", example: "That's my car.", category: "交通" },
        { word: "bus", definition: "公交车", example: "Take the bus.", category: "交通" },
        { word: "train", definition: "火车", example: "Take the train.", category: "交通" },
        { word: "airplane", definition: "飞机", example: "By airplane.", category: "交通" },
        { word: "bike", definition: "自行车", example: "Ride a bike.", category: "交通" },
        { word: "taxi", definition: "出租车", example: "Take a taxi.", category: "交通" },
        { word: "subway", definition: "地铁", example: "Subway is fast.", category: "交通" },
        { word: "boat", definition: "船", example: "Take a boat.", category: "交通" },
        { word: "ship", definition: "轮船", example: "Big ship.", category: "交通" },
        { word: "road", definition: "路", example: "Cross the road.", category: "交通" },
        { word: "street", definition: "街道", example: "The street is busy.", category: "交通" },
        { word: "traffic", definition: "交通", example: "Traffic jam.", category: "交通" },
        { word: "light", definition: "灯", example: "Traffic lights.", category: "交通" },
        { word: "red", definition: "红", example: "Red light stop.", category: "交通" },
        { word: "green", definition: "绿", example: "Green light go.", category: "交通" },
        { word: "yellow", definition: "黄", example: "Yellow light wait.", category: "交通" },
        { word: "stop", definition: "停止", example: "Stop here.", category: "交通" },
        { word: "wait", definition: "等待", example: "Wait for me.", category: "交通" },
        { word: "travel", definition: "旅行", example: "Travel abroad.", category: "交通" },
        { word: "trip", definition: "旅行", example: "Have a nice trip.", category: "交通" },
        { word: "journey", definition: "旅程", example: "Long journey.", category: "交通" },
        { word: "visit", definition: "拜访", example: "Visit my grandma.", category: "交通" },
        { word: "go out", definition: "外出", example: "Let's go out.", category: "交通" },
        { word: "stay", definition: "停留", example: "Stay here.", category: "交通" },
        { word: "hotel", definition: "酒店", example: "Stay in a hotel.", category: "交通" },
        { word: "restaurant", definition: "餐厅", example: "Eat at restaurant.", category: "交通" },
        { word: "shop", definition: "商店", example: "Go to the shop.", category: "交通" },
        { word: "park", definition: "公园", example: "Play in the park.", category: "交通" },
        { word: "zoo", definition: "动物园", example: "See animals at the zoo.", category: "交通" },
        { word: "cinema", definition: "电影院", example: "Go to the cinema.", category: "交通" },
        { word: "library", definition: "图书馆", example: "Read at library.", category: "交通" },
        { word: "hospital", definition: "医院", example: "Hospitals help sick people.", category: "交通" },
        { word: "supermarket", definition: "超市", example: "Buy food at supermarket.", category: "交通" },
        { word: "market", definition: "市场", example: "Fresh food at market.", category: "交通" },
        { word: "city", definition: "城市", example: "Big city.", category: "交通" },
        { word: "town", definition: "小镇", example: "Small town.", category: "交通" },
        { word: "village", definition: "村庄", example: "Village is quiet.", category: "交通" },
        { word: "country", definition: "国家", example: "My country.", category: "交通" },
        { word: "world", definition: "世界", example: "Around the world.", category: "交通" },
        { word: "map", definition: "地图", example: "Look at the map.", category: "交通" },
        { word: "left", definition: "左", example: "Turn left.", category: "交通" },
        { word: "right", definition: "右", example: "Turn right.", category: "交通" },
        { word: "straight", definition: "直走", example: "Go straight.", category: "交通" },
        { word: "far", definition: "远", example: "Is it far?", category: "交通" },
        { word: "near", definition: "近", example: "My home is near.", category: "交通" },
        { word: "fast", definition: "快", example: "Run fast.", category: "交通" },
        { word: "slow", definition: "慢", example: "Drive slow.", category: "交通" }
    ],
    "时间数字场景": [
        { word: "time", definition: "时间", example: "What time is it?", category: "时间" },
        { word: "clock", definition: "时钟", example: "Look at the clock.", category: "时间" },
        { word: "watch", definition: "手表", example: "I have a watch.", category: "时间" },
        { word: "morning", definition: "上午", example: "Good morning.", category: "时间" },
        { word: "afternoon", definition: "下午", example: "Good afternoon.", category: "时间" },
        { word: "evening", definition: "晚上", example: "Good evening.", category: "时间" },
        { word: "night", definition: "夜晚", example: "Good night.", category: "时间" },
        { word: "today", definition: "今天", example: "Today is Monday.", category: "时间" },
        { word: "tomorrow", definition: "明天", example: "See you tomorrow.", category: "时间" },
        { word: "yesterday", definition: "昨天", example: "Yesterday was Sunday.", category: "时间" },
        { word: "day", definition: "天", example: "Seven days a week.", category: "时间" },
        { word: "week", definition: "周", example: "This week.", category: "时间" },
        { word: "weekend", definition: "周末", example: "Happy weekend!", category: "时间" },
        { word: "month", definition: "月", example: "January is a month.", category: "时间" },
        { word: "year", definition: "年", example: "New Year.", category: "时间" },
        { word: "Monday", definition: "星期一", example: "Monday morning.", category: "时间" },
        { word: "Tuesday", definition: "星期二", example: "Tuesday is busy.", category: "时间" },
        { word: "Wednesday", definition: "星期三", example: "Wednesday is mid-week.", category: "时间" },
        { word: "Thursday", definition: "星期四", example: "Thursday evening.", category: "时间" },
        { word: "Friday", definition: "星期五", example: "Friday is fun!", category: "时间" },
        { word: "Saturday", definition: "星期六", example: "Saturday is free.", category: "时间" },
        { word: "Sunday", definition: "星期日", example: "Sunday is rest day.", category: "时间" },
        { word: "January", definition: "一月", example: "January is cold.", category: "时间" },
        { word: "February", definition: "二月", example: "February has 28 days.", category: "时间" },
        { word: "March", definition: "三月", example: "March comes after February.", category: "时间" },
        { word: "April", definition: "四月", example: "April showers.", category: "时间" },
        { word: "May", definition: "五月", example: "May is warm.", category: "时间" },
        { word: "June", definition: "六月", example: "June is summer.", category: "时间" },
        { word: "July", definition: "七月", example: "July is hot.", category: "时间" },
        { word: "August", definition: "八月", example: "August is vacation.", category: "时间" },
        { word: "September", definition: "九月", example: "September is school time.", category: "时间" },
        { word: "October", definition: "十月", example: "October is cool.", category: "时间" },
        { word: "November", definition: "十一月", example: "November is autumn.", category: "时间" },
        { word: "December", definition: "十二月", example: "December is Christmas.", category: "时间" },
        { word: "one", definition: "一", example: "One apple.", category: "数字" },
        { word: "two", definition: "二", example: "Two dogs.", category: "数字" },
        { word: "three", definition: "三", example: "Three books.", category: "数字" },
        { word: "four", definition: "四", example: "Four chairs.", category: "数字" },
        { word: "five", definition: "五", example: "Five fingers.", category: "数字" },
        { word: "six", definition: "六", example: "Six eggs.", category: "数字" },
        { word: "seven", definition: "七", example: "Seven days.", category: "数字" },
        { word: "eight", definition: "八", example: "Eight crayons.", category: "数字" },
        { word: "nine", definition: "九", example: "Nine cookies.", category: "数字" },
        { word: "ten", definition: "十", example: "Ten kids.", category: "数字" },
        { word: "eleven", definition: "十一", example: "Eleven players.", category: "数字" },
        { word: "twelve", definition: "十二", example: "Twelve months.", category: "数字" },
        { word: "thirteen", definition: "十三", example: "Thirteen is unlucky.", category: "数字" },
        { word: "fourteen", definition: "十四", example: "Fourteen years old.", category: "数字" },
        { word: "fifteen", definition: "十五", example: "Fifteen minutes.", category: "数字" },
        { word: "sixteen", definition: "十六", example: "Sweet sixteen.", category: "数字" },
        { word: "seventeen", definition: "十七", example: "Seventeen years.", category: "数字" },
        { word: "eighteen", definition: "十八", example: "Eighteen is adult.", category: "数字" },
        { word: "nineteen", definition: "十九", example: "Nineteen cards.", category: "数字" },
        { word: "twenty", definition: "二十", example: "Twenty students.", category: "数字" },
        { word: "thirty", definition: "三十", example: "Thirty days.", category: "数字" },
        { word: "forty", definition: "四十", example: "Forty winks.", category: "数字" },
        { word: "fifty", definition: "五十", example: "Fifty cents.", category: "数字" },
        { word: "hundred", definition: "一百", example: "One hundred dollars.", category: "数字" },
        { word: "thousand", definition: "一千", example: "A thousand miles.", category: "数字" },
        { word: "first", definition: "第一", example: "First place.", category: "数字" },
        { word: "second", definition: "第二", example: "Second prize.", category: "数字" },
        { word: "third", definition: "第三", example: "Third time.", category: "数字" },
        { word: "fourth", definition: "第四", example: "Fourth floor.", category: "数字" },
        { word: "fifth", definition: "第五", example: "Fifth element.", category: "数字" },
        { word: "many", definition: "许多", example: "Many people.", category: "数字" },
        { word: "few", definition: "很少", example: "Few friends.", category: "数字" },
        { word: "some", definition: "一些", example: "Some water.", category: "数字" },
        { word: "any", definition: "任何", example: "Any questions?", category: "数字" },
        { word: "all", definition: "全部", example: "All done.", category: "数字" },
        { word: "every", definition: "每个", example: "Every day.", category: "数字" },
        { word: "each", definition: "每个", example: "Each student.", category: "数字" },
        { word: "no", definition: "没有", example: "No money.", category: "数字" },
        { word: "more", definition: "更多", example: "More please.", category: "数字" },
        { word: "less", definition: "更少", example: "Less sugar.", category: "数字" },
        { word: "most", definition: "最多", example: "Most people.", category: "数字" },
        { word: "least", definition: "最少", example: "Least effort.", category: "数字" },
        { word: "big", definition: "大的", example: "Big house.", category: "数字" },
        { word: "small", definition: "小的", example: "Small dog.", category: "数字" },
        { word: "tall", definition: "高的", example: "Tall man.", category: "数字" },
        { word: "short", definition: "矮的", example: "Short girl.", category: "数字" },
        { word: "long", definition: "长的", example: "Long hair.", category: "数字" },
        { word: "young", definition: "年轻的", example: "Young kid.", category: "数字" },
        { word: "old", definition: "老的", example: "Old tree.", category: "数字" },
        { word: "early", definition: "早", example: "Early morning.", category: "时间" },
        { word: "late", definition: "晚", example: "Don't be late.", category: "时间" },
        { word: "quick", definition: "快", example: "Quick decision.", category: "时间" },
        { word: "now", definition: "现在", example: "Do it now.", category: "时间" },
        { word: "then", definition: "然后", example: "Then go home.", category: "时间" },
        { word: "soon", definition: "很快", example: "See you soon.", category: "时间" },
        { word: "never", definition: "从不", example: "I never lie.", category: "时间" },
        { word: "always", definition: "总是", example: "Always smile.", category: "时间" },
        { word: "often", definition: "经常", example: "I often visit.", category: "时间" },
        { word: "sometimes", definition: "有时", example: "Sometimes it rains.", category: "时间" },
        { word: "usually", definition: "通常", example: "I usually walk.", category: "时间" }
    ],
    "自然天气场景": [
        { word: "sun", definition: "太阳", example: "The sun is hot.", category: "自然" },
        { word: "moon", definition: "月亮", example: "Moon is beautiful.", category: "自然" },
        { word: "star", definition: "星星", example: "Stars twinkle.", category: "自然" },
        { word: "sky", definition: "天空", example: "Blue sky.", category: "自然" },
        { word: "cloud", definition: "云", example: "White clouds.", category: "自然" },
        { word: "rain", definition: "雨", example: "It's raining.", category: "自然" },
        { word: "snow", definition: "雪", example: "Snow is white.", category: "自然" },
        { word: "wind", definition: "风", example: "Strong wind.", category: "自然" },
        { word: "storm", definition: "暴风雨", example: "Big storm coming.", category: "自然" },
        { word: "weather", definition: "天气", example: "Nice weather.", category: "自然" },
        { word: "hot", definition: "热的", example: "It's hot today.", category: "自然" },
        { word: "cold", definition: "冷的", example: "Winter is cold.", category: "自然" },
        { word: "warm", definition: "暖和的", example: "Warm sunshine.", category: "自然" },
        { word: "cool", definition: "凉爽的", example: "Cool breeze.", category: "自然" },
        { word: "sunny", definition: "晴朗的", example: "Sunny day.", category: "自然" },
        { word: "rainy", definition: "下雨的", example: "Rainy afternoon.", category: "自然" },
        { word: "cloudy", definition: "多云的", example: "Cloudy sky.", category: "自然" },
        { word: "windy", definition: "有风的", example: "Windy day.", category: "自然" },
        { word: "snowy", definition: "下雪的", example: "Snowy night.", category: "自然" },
        { word: "foggy", definition: "有雾的", example: "Foggy morning.", category: "自然" },
        { word: "spring", definition: "春天", example: "Spring is green.", category: "自然" },
        { word: "summer", definition: "夏天", example: "Summer is hot.", category: "自然" },
        { word: "autumn", definition: "秋天", example: "Autumn leaves.", category: "自然" },
        { word: "fall", definition: "秋天", example: "Fall colors.", category: "自然" },
        { word: "winter", definition: "冬天", example: "Winter is cold.", category: "自然" },
        { word: "season", definition: "季节", example: "Four seasons.", category: "自然" },
        { word: "tree", definition: "树", example: "Big tree.", category: "自然" },
        { word: "flower", definition: "花", example: "Beautiful flower.", category: "自然" },
        { word: "grass", definition: "草", example: "Green grass.", category: "自然" },
        { word: "leaf", definition: "叶子", example: "Yellow leaf.", category: "自然" },
        { word: "plant", definition: "植物", example: "Green plant.", category: "自然" },
        { word: "animal", definition: "动物", example: "Farm animals.", category: "自然" },
        { word: "bird", definition: "鸟", example: "Birds sing.", category: "自然" },
        { word: "cat", definition: "猫", example: "Fluffy cat.", category: "自然" },
        { word: "dog", definition: "狗", example: "Loyal dog.", category: "自然" },
        { word: "fish", definition: "鱼", example: "Swim like fish.", category: "自然" },
        { word: "horse", definition: "马", example: "Fast horse.", category: "自然" },
        { word: "cow", definition: "牛", example: "Milk cow.", category: "自然" },
        { word: "pig", definition: "猪", example: "Fat pig.", category: "自然" },
        { word: "chicken", definition: "鸡", example: "Farm chicken.", category: "自然" },
        { word: "duck", definition: "鸭子", example: "Swimming duck.", category: "自然" },
        { word: "sheep", definition: "羊", example: "White sheep.", category: "自然" },
        { word: "elephant", definition: "大象", example: "Big elephant.", category: "自然" },
        { word: "lion", definition: "狮子", example: "King lion.", category: "自然" },
        { word: "tiger", definition: "老虎", example: "Strong tiger.", category: "自然" },
        { word: "monkey", definition: "猴子", example: "Funny monkey.", category: "自然" },
        { word: "snake", definition: "蛇", example: "Watch out for snakes!", category: "自然" },
        { word: "insect", definition: "昆虫", example: "Bee is insect.", category: "自然" },
        { word: "bee", definition: "蜜蜂", example: "Busy bee.", category: "自然" },
        { word: "ant", definition: "蚂蚁", example: "Little ant.", category: "自然" },
        { word: "water", definition: "水", example: "Clean water.", category: "自然" },
        { word: "sea", definition: "海", example: "Blue sea.", category: "自然" },
        { word: "ocean", definition: "海洋", example: "Deep ocean.", category: "自然" },
        { word: "river", definition: "河", example: "Long river.", category: "自然" },
        { word: "lake", definition: "湖", example: "Quiet lake.", category: "自然" },
        { word: "mountain", definition: "山", example: "High mountain.", category: "自然" },
        { word: "hill", definition: "小山", example: "Climb the hill.", category: "自然" },
        { word: "forest", definition: "森林", example: "Dark forest.", category: "自然" },
        { word: "beach", definition: "海滩", example: "Beautiful beach.", category: "自然" },
        { word: "sand", definition: "沙子", example: "Sand castle.", category: "自然" },
        { word: "rock", definition: "石头", example: "Big rock.", category: "自然" },
        { word: "ground", definition: "地面", example: "Sit on the ground.", category: "自然" },
        { word: "earth", definition: "地球", example: "Our planet Earth.", category: "自然" },
        { word: "world", definition: "世界", example: "Travel the world.", category: "自然" },
        { word: "nature", definition: "自然", example: "Love nature.", category: "自然" },
        { word: "beautiful", definition: "美丽的", example: "Beautiful sunset.", category: "自然" },
        { word: "ugly", definition: "丑陋的", example: "That's ugly.", category: "自然" },
        { word: "clean", definition: "干净的", example: "Clean river.", category: "自然" },
        { word: "dirty", definition: "脏的", example: "Dirty water.", category: "自然" },
        { word: "bright", definition: "明亮的", example: "Bright sun.", category: "自然" },
        { word: "dark", definition: "黑暗的", example: "Dark night.", category: "自然" },
        { word: "quiet", definition: "安静的", example: "Quiet library.", category: "自然" },
        { word: "loud", definition: "大声的", example: "Loud music.", category: "自然" }
    ],
    "情绪性格场景": [
        { word: "happy", definition: "开心的", example: "I'm very happy.", category: "情绪" },
        { word: "sad", definition: "难过的", example: "I'm sad today.", category: "情绪" },
        { word: "angry", definition: "生气的", example: "Don't be angry.", category: "情绪" },
        { word: "excited", definition: "激动的", example: "I'm so excited!", category: "情绪" },
        { word: "surprised", definition: "惊讶的", example: "I'm surprised!", category: "情绪" },
        { word: "afraid", definition: "害怕的", example: "I'm afraid of the dark.", category: "情绪" },
        { word: "tired", definition: "累的", example: "I'm tired.", category: "情绪" },
        { word: "hungry", definition: "饿的", example: "I'm hungry.", category: "情绪" },
        { word: "thirsty", definition: "渴的", example: "I'm thirsty.", category: "情绪" },
        { word: "bored", definition: "无聊的", example: "I'm bored.", category: "情绪" },
        { word: "interested", definition: "感兴趣的", example: "I'm interested.", category: "情绪" },
        { word: "worried", definition: "担心的", example: "Don't be worried.", category: "情绪" },
        { word: "nervous", definition: "紧张的", example: "I'm nervous.", category: "情绪" },
        { word: "calm", definition: "冷静的", example: "Stay calm.", category: "情绪" },
        { word: "proud", definition: "自豪的", example: "I'm proud of you.", category: "情绪" },
        { word: "shy", definition: "害羞的", example: "She is shy.", category: "情绪" },
        { word: "brave", definition: "勇敢的", example: "Be brave.", category: "情绪" },
        { word: "kind", definition: "友善的", example: "She is very kind.", category: "性格" },
        { word: "nice", definition: "美好的", example: "Nice to meet you.", category: "性格" },
        { word: "friendly", definition: "友好的", example: "Friendly smile.", category: "性格" },
        { word: "helpful", definition: "乐于助人的", example: "Helpful student.", category: "性格" },
        { word: "funny", definition: "有趣的", example: "He is very funny.", category: "性格" },
        { word: "clever", definition: "聪明的", example: "Clever boy.", category: "性格" },
        { word: "smart", definition: "聪明的", example: "She is smart.", category: "性格" },
        { word: "stupid", definition: "愚蠢的", example: "That was stupid.", category: "性格" },
        { word: "lazy", definition: "懒惰的", example: "Don't be lazy.", category: "性格" },
        { word: "hardworking", definition: "努力的", example: "Hardworking student.", category: "性格" },
        { word: "careful", definition: "小心的", example: "Be careful.", category: "性格" },
        { word: "careless", definition: "粗心的", example: "Don't be careless.", category: "性格" },
        { word: "polite", definition: "有礼貌的", example: "Polite boy.", category: "性格" },
        { word: "rude", definition: "粗鲁的", example: "Don't be rude.", category: "性格" },
        { word: "quiet", definition: "安静的", example: "Quiet girl.", category: "性格" },
        { word: "active", definition: "活跃的", example: "Active kid.", category: "性格" },
        { word: "cute", definition: "可爱的", example: "Cute puppy.", category: "性格" },
        { word: "love", definition: "爱", example: "I love you.", category: "情绪" },
        { word: "like", definition: "喜欢", example: "I like it.", category: "情绪" },
        { word: "hate", definition: "讨厌", example: "I hate that.", category: "情绪" },
        { word: "want", definition: "想要", example: "What do you want?", category: "情绪" },
        { word: "need", definition: "需要", example: "I need help.", category: "情绪" },
        { word: "wish", definition: "希望", example: "Make a wish.", category: "情绪" },
        { word: "hope", definition: "希望", example: "I hope so.", category: "情绪" },
        { word: "feel", definition: "感觉", example: "How do you feel?", category: "情绪" },
        { word: "think", definition: "想", example: "What do you think?", category: "情绪" },
        { word: "know", definition: "知道", example: "I know that.", category: "情绪" },
        { word: "understand", definition: "理解", example: "I understand.", category: "情绪" },
        { word: "remember", definition: "记住", example: "Remember this.", category: "情绪" },
        { word: "forget", definition: "忘记", example: "Don't forget.", category: "情绪" },
        { word: "believe", definition: "相信", example: "I believe you.", category: "情绪" },
        { word: "trust", definition: "信任", example: "Trust me.", category: "情绪" },
        { word: "promise", definition: "承诺", example: "I promise.", category: "情绪" }
    ]
};

// 统计单词总数
let totalWordCount = 0;
for (const scene in ketVocabularyScene) {
    totalWordCount += ketVocabularyScene[scene].length;
}
console.log("KET单词库总词数:", totalWordCount);
